# 1. A URL sem o usuário e a senha dentro dela
quarkus.datasource.jdbc.url=${DB_JDBC_URL:jdbc:postgresql://ep-solitary-thunder-a4kaesgr.us-east-1.aws.neon.tech/neondb?sslmode=require}

# 2. O usuário separado
quarkus.datasource.username=${DB_USERNAME:neondb_owner}

# 3. A senha separada
quarkus.datasource.password=${DB_PASSWORD:npg_9dtUqXpH3sxa}

# 4. Tipo do banco
quarkus.datasource.db-kind=postgresql

# Isso aqui desativa a necessidade de Docker no seu PC
quarkus.devservices.enabled=false
quarkus.hibernate-orm.database.generation=update

# CORS (dev / Vite em http://localhost:5173)
%dev.quarkus.http.cors.enabled=true
%dev.quarkus.http.cors.origins=http://localhost:5173,http://127.0.0.1:5173
%dev.quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
%dev.quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with

quarkus.http.host=0.0.0.0
quarkus.http.port=${PORT:8080}

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=https://az-construct-flow.vercel.app
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization